---


as3_virtual_address: "{{ hostvars[groups['F5_systems'][0]].vs_ip }}"
bigip_username_encoded: "{{ 'admin' | string | b64encode }}"
bigip_pass: "{{ lookup('env', 'BIGIP_PASS') }}"
bigip_pass_encoded: "{{ lookup('vars', 'bigip_pass') | string | b64encode }}"
bigip_mgmt_port: 8443
robin_bucket: "tky-robin-lab1"
robin_install_path: "robin-install-k8s_5.3.0-198.sh" 
robin_install_local_path: "/tmp/robin-install-k8s_5.3.0-198.sh"
robin_binimg_path: "robinbinimg-5.3.0-198.tar.gz" 
robin_binimg_local_path: "/tmp/robinbinimg-5.3.0-198.tar.gz"
robin_k8s_path: "k8s-images-5.3.0-198.tar.gz" 
robin_k8s_local_path: "/tmp/k8s-images-5.3.0-198.tar.gz"
ssh_port: 22